Repository microsoft/DeepGNN, pull requests merged in 2022-08, with the labels that each got.

#65 Sort edges by type
  CHANGELOG.md
  src/python/deepgnn/graph_engine/snark/decoders.py
  src/python/deepgnn/graph_engine/snark/tests/convert_test.py
Labels: bug

#66 Handle empty sparse features
  CHANGELOG.md
  src/cc/lib/graph/partition.cc
  src/python/deepgnn/graph_engine/snark/converter/writers.py
  src/python/deepgnn/graph_engine/snark/tests/sparse_features_test.py
Labels: bug

#67 Use latest grpc/abseil
  WORKSPACE
  examples/hdfs_setup.sh
  src/cc/lib/BUILD
  src/cc/lib/distributed/BUILD
  src/cc/lib/graph/BUILD
Labels: dependencies

#70 Fix hdfs edge features filename.
  src/cc/lib/graph/partition.cc
Labels: bug

#71 Add changelog to PR template checklist.
  .github/PULL_REQUEST_TEMPLATE
Labels: documentation

#73 Make use of run_args in torch docs. Remove tf from torch docs reqs.
  docs/torch/link_pred.rst
  docs/torch/node_class.rst
Labels: documentation

#74 Add rtd config
  .readthedocs.yaml
  WORKSPACE
  docs/BUILD
  docs/graph_engine/data_spec.rst
  docs/requirements.txt
Labels: documentation

#44 Neighbor Count Functionality for Memory/Distributed Graphs
  CHANGELOG.md
  src/cc/lib/distributed/call_data.cc
  src/cc/lib/distributed/call_data.h
  src/cc/lib/distributed/client.cc
  src/cc/lib/distributed/client.h
  src/cc/lib/distributed/graph_engine.cc
  src/cc/lib/distributed/graph_engine.h
  src/cc/lib/distributed/server.cc
  src/cc/lib/distributed/service.proto
  src/cc/lib/graph/graph.cc
  src/cc/lib/graph/graph.h
  src/cc/lib/graph/partition.cc
  src/cc/lib/graph/partition.h
  src/cc/lib/py_graph.cc
  src/cc/lib/py_graph.h
  src/cc/lib/version-script.darwin.lds
  src/cc/lib/version-script.linux.lds
  src/cc/tests/distributed_test.cc
  src/cc/tests/graph_test.cc
  src/python/deepgnn/graph_engine/snark/client.py
  src/python/deepgnn/graph_engine/snark/local.py
  src/python/deepgnn/graph_engine/snark/tests/BUILD
  src/python/deepgnn/graph_engine/snark/tests/neighbor_sampler_test.py
Labels: enhancement

#77 Add generator to automatically pull e2e test ports.
  src/python/deepgnn/graph_engine/snark/tests/e2e_test.py
Labels: enhancement

#78 DeepGNNDataset cleanup.
  src/python/deepgnn/graph_engine/graph_dataset.py
  src/python/deepgnn/pytorch/common/dataset.py
  src/python/deepgnn/tf/common/dataset.py
Labels: enhancement

#58 Support nodes and their outgoing edges on different partitions.
  CHANGELOG.md
  docs/graph_engine/data_spec.rst
  src/cc/lib/distributed/graph_engine.cc
  src/cc/lib/graph/graph.cc
  src/cc/lib/graph/partition.cc
  src/cc/lib/graph/partition.h
  src/cc/lib/graph/types.h
  src/cc/tests/distributed_test.cc
  src/cc/tests/graph_test.cc
  src/cc/tests/mocks.cc
  src/python/deepgnn/graph_engine/snark/converter/writers.py
  src/python/deepgnn/graph_engine/snark/decoders.py
  src/python/deepgnn/graph_engine/snark/tests/e2e_test.py
  src/python/deepgnn/graph_engine/snark/tests/sparse_features_test.py
Labels: enhancement

#81 Don't skip empty sparse features
  CHANGELOG.md
  src/python/deepgnn/graph_engine/snark/client.py
  src/python/deepgnn/graph_engine/snark/tests/sparse_features_test.py
Labels: bug

#80 Introduce version for binary data.
  CHANGELOG.md
  docs/advanced/sql_shard.rst
  docs/graph_engine/data_spec.rst
  docs/graph_engine/spark_converter.rst
  src/cc/lib/benchmark/grpc_benchmark.cc
  src/cc/lib/benchmark/neighbor_sampler_benchmark.cc
  src/cc/lib/distributed/client.cc
  src/cc/lib/distributed/graph_engine.cc
  src/cc/lib/distributed/service.proto
  src/cc/lib/graph/metadata.cc
  src/cc/lib/graph/metadata.h
  src/cc/tests/distributed_test.cc
  src/cc/tests/mocks.cc
  src/python/deepgnn/graph_engine/backends/snark/client.py
  src/python/deepgnn/graph_engine/snark/convert.py
  src/python/deepgnn/graph_engine/snark/distributed.py
  src/python/deepgnn/graph_engine/snark/meta.py
  src/python/deepgnn/graph_engine/snark/meta_merger.py
  src/python/deepgnn/graph_engine/snark/tests/convert_test.py
Labels: enhancement
