Repository microsoft/DeepGNN, pull requests merged in 2022-10, with the labels that each got.

#59 Add Linear format.
  CHANGELOG.md
  docs/graph_engine/data_spec.rst
  src/cc/lib/distributed/graph_engine.cc
  src/cc/lib/graph/graph.cc
  src/cc/lib/graph/partition.cc
  src/cc/lib/graph/types.h
  src/python/deepgnn/graph_engine/data/citation.py
  src/python/deepgnn/graph_engine/data/data_util.py
  src/python/deepgnn/graph_engine/data/ppi.py
  src/python/deepgnn/graph_engine/snark/converter/writers.py
  src/python/deepgnn/graph_engine/snark/decoders.py
  src/python/deepgnn/graph_engine/snark/tests/BUILD
  src/python/deepgnn/graph_engine/snark/tests/convert_test.py
  src/python/deepgnn/graph_engine/snark/tests/e2e_test.py
  src/python/deepgnn/graph_engine/snark/tests/sparse_features_test.py
  src/python/deepgnn/graph_engine/snark/tests/util_test.py
Labels: enhancement

#46 Remove FeatureType enum, replace with np.dtype.
  .bazelrc
  .mypy.ini
  CHANGELOG.md
  README.md
  docs/graph_engine/overview.rst
  docs/tf/link_pred.rst
  docs/tf/node_class.rst
  docs/torch/link_pred.rst
  docs/torch/node_class.rst
  examples/pytorch/conftest.py
  examples/pytorch/gat/model.py
  examples/pytorch/geometric/gat/model_geometric.py
  examples/pytorch/geometric/graphsage/main.py
  examples/pytorch/geometric/graphsage/model.py
  examples/pytorch/geometric/graphsage/test_model.py
  examples/pytorch/graphsage/main.py
  examples/pytorch/graphsage/model.py
  examples/pytorch/graphsage/test_model.py
  examples/pytorch/hetgnn/main.py
  examples/pytorch/hetgnn/model.py
  examples/pytorch/hetgnn/test_args.py
  examples/pytorch/hetgnn/test_model.py
  examples/pytorch/knowledgegraph/model.py
  examples/pytorch/knowledgegraph/test_model.py
  examples/pytorch/link_prediction/main.py
  examples/pytorch/link_prediction/model.py
  examples/pytorch/link_prediction/test_model.py
  examples/pytorch/link_prediction/test_poolers.py
  examples/tensorflow/gat/gat.py
  examples/tensorflow/gcn/gcn.py
  examples/tensorflow/han/han.py
  examples/tensorflow/sage/sage.py
  src/python/deepgnn/graph_engine/_base.py
  src/python/deepgnn/graph_engine/backends/snark/test_snark_client.py
  src/python/deepgnn/graph_engine/data/test_graph_dataset.py
  src/python/deepgnn/graph_engine/graph_ops.py
  src/python/deepgnn/graph_engine/samplers.py
  src/python/deepgnn/graph_engine/snark/local.py
  src/python/deepgnn/graph_engine/snark/tests/snark_test.py
  src/python/deepgnn/migrate/0_1_56.py
  src/python/deepgnn/migrate/__init__.py
  src/python/deepgnn/pytorch/common/utils.py
  src/python/deepgnn/pytorch/encoding/feature_encoder.py
  src/python/deepgnn/pytorch/encoding/gnn_encoder_sage.py
  src/python/deepgnn/pytorch/encoding/test_feature_encoder.py
  src/python/deepgnn/pytorch/modeling/base_model.py
  src/python/deepgnn/tf/encoders/att_encoder.py
  src/python/setup.py
Labels: enhancement

#68 Add custom decoder example.
  docs/BUILD
  docs/graph_engine/custom_decoder.rst
  docs/graph_engine/index.rst
  requirements.txt
Labels: documentation

#98 Upgrade all requirements
  docs/tf/link_pred.rst
  examples/tensorflow/sage/test_sage.py
  requirements.txt
Labels: enhancement

#103 Add PR instructions
  CONTRIBUTING.md
Labels: documentation

#109 Fix torch dataset 1.10.2 type issue.
  src/python/deepgnn/graph_engine/graph_dataset.py
  src/python/deepgnn/pytorch/common/dataset.py
Labels: bug, enhancement
