Repository microsoft/DeepGNN, pull requests merged in 2022-11, with the labels that each got.

#111 Run all tests in e2e_test.py and sparse_feature_test.py
  src/python/deepgnn/graph_engine/snark/tests/e2e_test.py
  src/python/deepgnn/graph_engine/snark/tests/sparse_features_test.py
Labels: refactor

#106 Load each partition from separate folder.
  .bazelrc
  CHANGELOG.md
  docs/graph_engine/custom_decoder.rst
  docs/graph_engine/from_networkx.rst
  src/cc/lib/benchmark/grpc_benchmark.cc
  src/cc/lib/benchmark/neighbor_sampler_benchmark.cc
  src/cc/lib/benchmark/partition_benchmark.cc
  src/cc/lib/distributed/graph_engine.cc
  src/cc/lib/distributed/graph_engine.h
  src/cc/lib/distributed/graph_sampler.cc
  src/cc/lib/distributed/graph_sampler.h
  src/cc/lib/graph/graph.cc
  src/cc/lib/graph/graph.h
  src/cc/lib/graph/partition.cc
  src/cc/lib/graph/partition.h
  src/cc/lib/graph/sampler.cc
  src/cc/lib/graph/sampler.h
  src/cc/lib/py_graph.cc
  src/cc/lib/py_graph.h
  src/cc/lib/py_server.cc
  src/cc/tests/distributed_test.cc
  src/cc/tests/graph_test.cc
  src/cc/tests/hdfs_test.cc
  src/cc/tests/mocks.cc
  src/python/deepgnn/graph_engine/data/data_util.py
  src/python/deepgnn/graph_engine/snark/_downloader.py
  src/python/deepgnn/graph_engine/snark/client.py
  src/python/deepgnn/graph_engine/snark/distributed.py
  src/python/deepgnn/graph_engine/snark/local.py
  src/python/deepgnn/graph_engine/snark/server.py
  src/python/deepgnn/graph_engine/snark/tests/downloader_test.py
  src/python/deepgnn/graph_engine/snark/tests/e2e_test.py
  src/python/deepgnn/graph_engine/snark/tests/hdfs_test.py
  src/python/deepgnn/graph_engine/snark/tests/neighbor_sampler_test.py
  src/python/deepgnn/graph_engine/snark/tests/random_walk_test.py
  src/python/deepgnn/graph_engine/snark/tests/snark_test.py
  src/python/deepgnn/graph_engine/snark/tests/sparse_features_test.py
Labels: enhancement

#112 Update converter docs.
  src/python/deepgnn/graph_engine/snark/convert.py
Labels: bug

#113 Update python versions and related CI actions
  .github/actions/lint/action.yml
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .github/workflows/wheel.yml
  CONTRIBUTING.md
  examples/tensorflow/requirements.txt
  src/python/setup.py
Labels: enhancement, dependencies

#114 Feature data type docs.
  docs/graph_engine/data_spec.rst
  src/python/deepgnn/graph_engine/snark/decoders.py
Labels: bug

#117 Fix CVE-2007-4559
  src/python/deepgnn/pytorch/encoding/twinbert/deepspeed/nvidia_modeling.py
  src/python/deepgnn/pytorch/encoding/twinbert/deepspeed/nvidia_modeling_no_apex.py
Labels: bug

#116 Update cryptography package
  requirements.txt
Labels: dependencies

#115 Add get_feature_type -> get_python_type to changelog and migrate script.
  CHANGELOG.md
  src/python/deepgnn/migrate/0_1_57.py
Labels: documentation
