Repository microsoft/DeepGNN, pull requests merged in 2023-01, with the labels that each got.

#133 Add hyperparameter tuning example.
  docs/BUILD
  docs/advanced/index.rst
  docs/advanced/meta_opt.rst
Labels: documentation

#144 Update to latest bazel, grpc, etc.
  .bazelrc
  .github/actions/benchmarks/action.yml
  .github/actions/test/action.yml
  .github/actions/wheel/action.yml
  CONTRIBUTING.md
  WORKSPACE
  config/variables.bzl
  src/cc/tests/BUILD
  src/python/deepgnn/graph_engine/snark/_lib.py
  src/python/deepgnn/graph_engine/snark/tests/BUILD
  src/python/deepgnn/graph_engine/snark/tests/downloader_test.py
  src/python/deepgnn/graph_engine/snark/tests/e2e_test.py
  src/python/deepgnn/graph_engine/snark/tests/neighbor_sampler_test.py
  src/python/deepgnn/graph_engine/snark/tests/random_walk_test.py
  src/python/setup.py
Labels: dependencies

#146 Update mimalloc
  WORKSPACE
Labels: dependencies

#145 Add grpc options
  CHANGELOG.md
  WORKSPACE
  src/cc/lib/distributed/graph_engine.cc
  src/cc/lib/py_graph.cc
  src/cc/lib/py_graph.h
  src/python/deepgnn/graph_engine/snark/client.py
  src/python/deepgnn/graph_engine/snark/distributed.py
  src/python/deepgnn/graph_engine/snark/tests/e2e_test.py
Labels: enhancement, dependencies

#137 Add TF version of Ray usage.
  docs/BUILD
  docs/tf/index.rst
  docs/tf/ray_usage.rst
Labels: documentation

#153 Drop no-commit hook
  .pre-commit-config.yaml
Labels: bug

#148 Improve doctest stability.
  docs/BUILD
  docs/tf/ray_usage.rst
Labels: enhancement
