Repository microsoft/DeepGNN, pull requests merged in 2023-04, with the labels that each got.

#170 Generate meta.json instead of meta.txt.
  CHANGELOG.md
  WORKSPACE
  config/json.BUILD
  docs/graph_engine/custom_decoder.rst
  docs/graph_engine/data_spec.rst
  docs/graph_engine/spark_converter.rst
  examples/pytorch/knowledgegraph/tools/convert_kg_to_json.py
  src/cc/lib/benchmark/grpc_benchmark.cc
  src/cc/lib/benchmark/neighbor_sampler_benchmark.cc
  src/cc/lib/graph/BUILD
  src/cc/lib/graph/locator.cc
  src/cc/lib/graph/metadata.cc
  src/cc/lib/graph/metadata.h
  src/cc/lib/py_graph.cc
  src/cc/tests/distributed_test.cc
  src/cc/tests/mocks.cc
  src/python/deepgnn/graph_engine/backends/snark/client.py
  src/python/deepgnn/graph_engine/snark/client.py
  src/python/deepgnn/graph_engine/snark/convert.py
  src/python/deepgnn/graph_engine/snark/converter/process.py
  src/python/deepgnn/graph_engine/snark/converter/writers.py
  src/python/deepgnn/graph_engine/snark/dispatcher.py
  src/python/deepgnn/graph_engine/snark/distributed.py
  src/python/deepgnn/graph_engine/snark/meta.py
  src/python/deepgnn/graph_engine/snark/meta_merger.py
  src/python/deepgnn/graph_engine/snark/server.py
  src/python/deepgnn/graph_engine/snark/tests/convert_test.py
  src/python/deepgnn/graph_engine/snark/tests/e2e_test.py
  src/python/deepgnn/graph_engine/snark/tests/snark_test.py
  src/python/deepgnn/graph_engine/snark/tests/sparse_features_test.py
Labels: enhancement

#177 Wait for all thread handlers to fill call data queues
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .github/workflows/wheel.yml
  src/cc/lib/distributed/server.cc
  src/cc/lib/distributed/server.h
Labels: bug

#176 Temporal graph support
  CHANGELOG.md
  docs/BUILD
  docs/advanced/sql_shard.rst
  docs/graph_engine/custom_decoder.rst
  docs/graph_engine/spark_converter.rst
  docs/graph_engine/temporal.rst
  src/cc/lib/benchmark/BUILD
  src/cc/lib/benchmark/grpc_benchmark.cc
  src/cc/lib/benchmark/neighbor_sampler_benchmark.cc
  src/cc/lib/benchmark/partition_benchmark.cc
  src/cc/lib/distributed/call_data.cc
  src/cc/lib/distributed/call_data.h
  src/cc/lib/distributed/client.cc
  src/cc/lib/distributed/client.h
  src/cc/lib/distributed/graph_engine.cc
  src/cc/lib/distributed/graph_engine.h
  src/cc/lib/distributed/server.cc
  src/cc/lib/distributed/server.h
  src/cc/lib/distributed/service.proto
  src/cc/lib/graph/BUILD
  src/cc/lib/graph/graph.cc
  src/cc/lib/graph/graph.h
  src/cc/lib/graph/locator.cc
  src/cc/lib/graph/locator.h
  src/cc/lib/graph/metadata.cc
  src/cc/lib/graph/metadata.h
  src/cc/lib/graph/partition.cc
  src/cc/lib/graph/partition.h
  src/cc/lib/graph/storage.h
  src/cc/lib/graph/types.h
  src/cc/lib/py_graph.cc
  src/cc/lib/py_graph.h
  src/cc/lib/version-script.darwin.lds
  src/cc/lib/version-script.linux.lds
  src/cc/tests/BUILD
  src/cc/tests/distributed_test.cc
  src/cc/tests/graph_test.cc
  src/cc/tests/hdfs_test.cc
  src/cc/tests/mocks.cc
  src/cc/tests/mocks.h
  src/cc/tests/temporal_test.cc
  src/python/deepgnn/graph_engine/_base.py
  src/python/deepgnn/graph_engine/snark/client.py
  src/python/deepgnn/graph_engine/snark/convert.py
  src/python/deepgnn/graph_engine/snark/converter/process.py
  src/python/deepgnn/graph_engine/snark/converter/writers.py
  src/python/deepgnn/graph_engine/snark/decoders.py
  src/python/deepgnn/graph_engine/snark/dispatcher.py
  src/python/deepgnn/graph_engine/snark/local.py
  src/python/deepgnn/graph_engine/snark/meta.py
  src/python/deepgnn/graph_engine/snark/meta_merger.py
  src/python/deepgnn/graph_engine/snark/tests/BUILD
  src/python/deepgnn/graph_engine/snark/tests/convert_test.py
  src/python/deepgnn/graph_engine/snark/tests/e2e_test.py
  src/python/deepgnn/graph_engine/snark/tests/neighbor_sampler_test.py
  src/python/deepgnn/graph_engine/snark/tests/sparse_features_test.py
  src/python/deepgnn/graph_engine/snark/tests/temporal_test.py
  src/python/deepgnn/graph_engine/snark/tests/util_test.py
Labels: documentation, enhancement

#178 Release 0.1.60
  CHANGELOG.md
  docs/graph_engine/index.rst
  docs/graph_engine/temporal.rst
  src/python/setup.py
Labels: documentation
